-- Run in Supabase SQL Editor to expose the existing businesses table to the app.
-- Existing rows are preserved when moving the table from private to public.

do $$
begin
  if to_regclass('public.businesses') is null then
    if to_regclass('private.businesses') is not null then
      alter table private.businesses set schema public;
    elsif to_regclass('private.business') is not null then
      alter table private.business rename to businesses;
      alter table private.businesses set schema public;
    elsif to_regclass('public.business') is not null then
      alter table public.business rename to businesses;
    elsif to_regclass('public.business_profiles') is not null then
      alter table public.business_profiles rename to businesses;
    end if;
  end if;
end;
$$;

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  owner_email text not null,
  subtitle text,
  description_locale text default 'en',
  is_active boolean default false,
  supported_currencies text not null default 'AFN, USD, PKR',
  name text,
  user_id uuid not null
);

alter table public.businesses add column if not exists updated_at timestamptz not null default now();
alter table public.businesses add column if not exists owner_email text;
alter table public.businesses add column if not exists user_id uuid;

update public.businesses as business
set user_id = app_user.id
from public.users as app_user
where business.user_id is null
  and lower(app_user.email) = lower(business.owner_email);

alter table public.businesses alter column user_id set not null;

create or replace function public.current_app_user_id()
returns uuid
language sql
stable
security definer
set search_path = ''
as $$
  select app_user.id
  from public.users as app_user
  where lower(app_user.email) = lower((select auth.jwt() ->> 'email'))
  limit 1;
$$;

revoke all on function public.current_app_user_id() from public;
grant execute on function public.current_app_user_id() to authenticated;

create index if not exists businesses_owner_email_idx
  on public.businesses (owner_email);

create unique index if not exists businesses_one_active_per_owner
  on public.businesses (lower(owner_email))
  where is_active is true and owner_email is not null;

create or replace function public.set_businesses_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists businesses_updated_at on public.businesses;
create trigger businesses_updated_at
  before update on public.businesses
  for each row execute function public.set_businesses_updated_at();

alter table public.businesses enable row level security;
grant select, insert, update, delete on public.businesses to authenticated;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = 'businesses'
  loop
    execute format('drop policy %I on public.businesses', existing_policy.policyname);
  end loop;
end;
$$;

create policy businesses_select_own
  on public.businesses for select to authenticated
  using (user_id = (select public.current_app_user_id()));

create policy businesses_insert_own
  on public.businesses for insert to authenticated
  with check (user_id = (select public.current_app_user_id()));

create policy businesses_update_own
  on public.businesses for update to authenticated
  using (user_id = (select public.current_app_user_id()))
  with check (user_id = (select public.current_app_user_id()));

create policy businesses_delete_own
  on public.businesses for delete to authenticated
  using (user_id = (select public.current_app_user_id()));

-- Customer and cashbook rows must remain inside businesses owned by the signed-in user.
-- Remove existing policies on these tables first so an older broad policy cannot bypass these rules.
alter table public.customers enable row level security;
alter table public.cashbook enable row level security;
grant select, insert, update, delete on public.customers to authenticated;
grant select, insert, update, delete on public.cashbook to authenticated;

do $$
declare
  existing_policy record;
begin
  for existing_policy in
    select tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename in ('customers', 'cashbook')
  loop
    execute format('drop policy %I on public.%I', existing_policy.policyname, existing_policy.tablename);
  end loop;
end;
$$;

create policy customers_select_owned_business
  on public.customers for select to authenticated
  using (exists (
    select 1 from public.businesses as business
    where business.id = customers.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

create policy customers_insert_owned_business
  on public.customers for insert to authenticated
  with check (exists (
    select 1 from public.businesses as business
    where business.id = customers.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

create policy customers_update_owned_business
  on public.customers for update to authenticated
  using (exists (
    select 1 from public.businesses as business
    where business.id = customers.business_id
      and business.user_id = (select public.current_app_user_id())
  ))
  with check (exists (
    select 1 from public.businesses as business
    where business.id = customers.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

create policy customers_delete_owned_business
  on public.customers for delete to authenticated
  using (exists (
    select 1 from public.businesses as business
    where business.id = customers.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

create policy cashbook_select_owned_business
  on public.cashbook for select to authenticated
  using (exists (
    select 1 from public.businesses as business
    where business.id = cashbook.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

create policy cashbook_insert_owned_business
  on public.cashbook for insert to authenticated
  with check (exists (
    select 1 from public.businesses as business
    where business.id = cashbook.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

create policy cashbook_update_owned_business
  on public.cashbook for update to authenticated
  using (exists (
    select 1 from public.businesses as business
    where business.id = cashbook.business_id
      and business.user_id = (select public.current_app_user_id())
  ))
  with check (exists (
    select 1 from public.businesses as business
    where business.id = cashbook.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

create policy cashbook_delete_owned_business
  on public.cashbook for delete to authenticated
  using (exists (
    select 1 from public.businesses as business
    where business.id = cashbook.business_id
      and business.user_id = (select public.current_app_user_id())
  ));

notify pgrst, 'reload schema';
