-- Run in Supabase SQL Editor to expose the existing businesses table to the app.
-- Existing rows are preserved when moving the table from private to public.

do $$
begin
  if to_regclass('public.businesses') is null then
    if to_regclass('private.businesses') is not null then
      alter table private.businesses set schema public;
    elsif to_regclass('private.business') is not null then
      alter table private.business rename to businesses;
      alter table private.businesses set schema public;
    elsif to_regclass('public.business') is not null then
      alter table public.business rename to businesses;
    elsif to_regclass('public.business_profiles') is not null then
      alter table public.business_profiles rename to businesses;
    end if;
  end if;
end;
$$;

create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  owner_email text not null,
  subtitle text,
  description_locale text default 'en',
  is_active boolean default false,
  supported_currencies text not null default 'AFN, USD, PKR',
  name text
);

alter table public.businesses add column if not exists updated_at timestamptz not null default now();
alter table public.businesses add column if not exists owner_email text;

create index if not exists businesses_owner_email_idx
  on public.businesses (owner_email);

create unique index if not exists businesses_one_active_per_owner
  on public.businesses (lower(owner_email))
  where is_active is true and owner_email is not null;

create or replace function public.set_businesses_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists businesses_updated_at on public.businesses;
create trigger businesses_updated_at
  before update on public.businesses
  for each row execute function public.set_businesses_updated_at();

alter table public.businesses enable row level security;
grant select, insert, update, delete on public.businesses to authenticated;

drop policy if exists businesses_select_own on public.businesses;
create policy businesses_select_own
  on public.businesses for select to authenticated
  using (lower(owner_email) = lower((select auth.jwt() ->> 'email')));

drop policy if exists businesses_insert_own on public.businesses;
create policy businesses_insert_own
  on public.businesses for insert to authenticated
  with check (lower(owner_email) = lower((select auth.jwt() ->> 'email')));

drop policy if exists businesses_update_own on public.businesses;
create policy businesses_update_own
  on public.businesses for update to authenticated
  using (lower(owner_email) = lower((select auth.jwt() ->> 'email')))
  with check (lower(owner_email) = lower((select auth.jwt() ->> 'email')));

drop policy if exists businesses_delete_own on public.businesses;
create policy businesses_delete_own
  on public.businesses for delete to authenticated
  using (lower(owner_email) = lower((select auth.jwt() ->> 'email')));

notify pgrst, 'reload schema';
